name: LunarLander-GA

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 355  # 5 hours 55 minutes

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gymnasium numpy argparse
      
      - name: Linting (Optional)
        run: |
          pip install flake8
          flake8 .

      - name: Train the policy
        run: |
          python train_agent.py --train --filename best_policy.npy
